DemoShop/DemoShop.Web/Models/HomeViewModel.cs
namespace DemoShop.Web.Models
{
    using System.Collections.Generic;

    public class HomeViewModel
    {
        public IEnumerable<ProductDetailsViewModel> Products { get; set; }
    }
}

DemoShop/DemoShop.Web/Controllers/HomeController.cs
namespace DemoShop.Web.Controllers
{
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using Models;
    using Services.Interfaces;

    public class HomeController : Controller
    {
        private readonly IProductsService productsService;

        public HomeController(IProductsService productsService)
            => this.productsService = productsService;

        public async Task<IActionResult> Index()
        {
            var serviceProducts = await this.productsService.GetAllAsync();

            var viewProducts = serviceProducts.Select(p => new ProductDetailsViewModel
            {
                Id = p.Id,
                Name = p.Name,
                Price = p.Price,
                ImageUrl = p.ImageUrl
            }).ToArray();

            var homeViewModel = new HomeViewModel
            {
                Products = viewProducts
            };

            return this.View(homeViewModel);
        }
    }
}

DemoShop/DemoShop.Web/Controllers/OrdersController.cs
namespace DemoShop.Web.Controllers
{
    using System;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using Models;
    using Services.Interfaces;
    using Services.Models.Order;

    [Authorize]
    public class OrdersController : Controller
    {
        public const string CardPaymentMethodName = "Card";
        public const string DirectPaymentMethodName = "Direct";

        private readonly IOrdersService ordersService;

        public OrdersController(IOrdersService ordersService)
            => this.ordersService = ordersService;

        public async Task<IActionResult> My()
        {
            var orders = (await this.ordersService.GetAllForUserAsync(this.User.Identity.Name))
                .Select(o => new OrderDetailsViewModel
                {
                    Id = o.Id,
                    CreatedOn = o.CreatedOn,
                    ProductName = o.ProductName,
                    ProductImageUrl = o.ProductImageUrl,
                    ProductPrice = o.ProductPrice,
                    PaymentStatus = o.PaymentStatus
                })
                .ToArray();

            return this.View(orders);
        }

        [HttpPost]
        public async Task<IActionResult> OrderProduct(string productId, string paymentMethod)
        {
            if (productId == null)
            {
                return this.RedirectToAction("Index", "Home");
            }

            var serviceModel = new OrderCreateServiceModel
            {
                ProductId = productId,
                CreatedOn = DateTime.UtcNow,
                UserName = this.User.Identity.Name
            };

            string orderId = await this.ordersService.CreateAsync(serviceModel);

            if (orderId == null)
            {
                return this.RedirectToAction("Index", "Home");
            }

            if (paymentMethod == DirectPaymentMethodName)
            {
                return this.RedirectToAction("Pay", "DirectPayments", new {id = orderId});
            }

            if (paymentMethod == CardPaymentMethodName)
            {
                return this.RedirectToAction("Pay", "CardPayments", new {id = orderId});
            }

            return this.RedirectToAction("My");
        }
    }
}

DemoShop/DemoShop.Web/Controllers/ProductsController.cs
namespace DemoShop.Web.Controllers
{
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using Models;
    using Services.Interfaces;
    using Services.Models.Product;

    [Authorize]
    public class ProductsController : Controller
    {
        private readonly IProductsService productsService;

        public ProductsController(IProductsService productsService)
            => this.productsService = productsService;

        public IActionResult Create()
            => this.View();

        [HttpPost]
        public async Task<IActionResult> Create(ProductCreateBindingModel model)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(model);
            }

            var serviceProduct = new ProductCreateServiceModel
            {
                Name = model.Name,
                Price = model.Price,
                ImageUrl = model.ImageUrl
            };

            await this.productsService.CreateAsync(serviceProduct);

            return this.RedirectToAction("Index", "Home");
        }
    }
}

DemoShop/DemoShop.Web/Views/Home/Index.cshtml
@using DemoShop.Web.Controllers
@model HomeViewModel
@{
    ViewData["Title"] = "Home Page";
}

<h1 class="text-center">Products</h1>
<div class="row my-3">
    @foreach (var product in Model.Products)
    {
        <div class="col-12 col-md-4 p-2 mx-auto">
            <div class="card shadow">
                <img class="card-img-top product-thumbnail-img" src="@product.ImageUrl" alt="@product.Name">
                <div class="card-body">
                    <h4 class="card-title">@product.Name</h4>
                    <p class="card-text">€@product.Price</p>
                    @if (User.Identity.IsAuthenticated)
                    {
                        <button class="btn btn-primary" data-toggle="modal" data-target="#orderModal"
                                data-id="@product.Id" data-name="@product.Name" data-price="@product.Price">
                            Buy now
                        </button>
                    }
                    else
                    {
                        <a class="btn btn-primary" asp-area="Identity" asp-page="/Account/Login">Buy now</a>
                    }
                </div>
            </div>
        </div>
    }
</div>

<div class="text-center">
    <a class="btn btn-outline-primary" asp-controller="Products" asp-action="Create">
        <i class="fas fa-plus"></i> Create product
    </a>
</div>

@if (User.Identity.IsAuthenticated)
{
    <div class="modal fade" id="orderModal" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title"></h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body"></div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary mr-auto" data-dismiss="modal">Cancel</button>

                    <form asp-action="OrderProduct" asp-controller="Orders" method="post">
                        <input type="hidden" name="productId">
                        <button type="submit" class="btn btn-info" name="paymentMethod"
                                value="@OrdersController.CardPaymentMethodName">
                            Pay by card
                        </button>
                        <button type="submit" class="btn btn-primary" name="paymentMethod"
                                value="@OrdersController.DirectPaymentMethodName">
                            Direct payment
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
}

@section Scripts {
    @if (User.Identity.IsAuthenticated)
    {
        <script>
            $('#orderModal').on('show.bs.modal',
                function(event) {
                    var button = $(event.relatedTarget);
                    var id = button.data('id');
                    var name = button.data('name');
                    var price = button.data('price');
                    var modal = $(this);
                    modal.find('.modal-title').text('Order ' + name);
                    modal.find('.modal-body').text('Price: €' + price);
                    modal.find('.modal-footer input[name=productId]').val(id);
                });
        </script>
    }
}