Web/BankSystem.Web/Areas/MoneyTransfers/Models/Global/Create/GlobalMoneyTransferCreateBindingModel.cs
namespace BankSystem.Web.Areas.MoneyTransfers.Models.Global.Create
{
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using Common;
    using Common.AutoMapping.Interfaces;
    using Infrastructure.Helpers.GlobalTransferHelpers.Models;
    using Web.Models.BankAccount;

    public class GlobalMoneyTransferCreateBindingModel : IMapWith<GlobalTransferDto>
    {
        [Required]
        public GlobalMoneyTransferCreateDestinationBankDto DestinationBank { get; set; }

        [MaxLength(ModelConstants.MoneyTransfer.DescriptionMaxLength)]
        [Display(Name = "Details of Payment")]
        public string Description { get; set; }

        [Required]
        [Range(typeof(decimal), ModelConstants.MoneyTransfer.MinStartingPrice,
            ModelConstants.MoneyTransfer.MaxStartingPrice,
            ErrorMessage = "The Amount field cannot be lower than 0.01")]
        public decimal Amount { get; set; }

        [Display(Name = "Name")]
        [MaxLength(ModelConstants.User.FullNameMaxLength)]
        public string SenderName { get; set; }

        public IEnumerable<OwnBankAccountListingViewModel> OwnAccounts { get; set; }

        [Required]
        [Display(Name = "From Account")]
        public string AccountId { get; set; }
    }
}

Web/BankSystem.Web/Areas/MoneyTransfers/Models/Global/Create/GlobalMoneyTransferCreateDestinationAccountDto.cs
namespace BankSystem.Web.Areas.MoneyTransfers.Models.Global.Create
{
    using System.ComponentModel.DataAnnotations;
    using Common;

    public class GlobalMoneyTransferCreateDestinationAccountDto
    {
        [Required]
        [MaxLength(ModelConstants.BankAccount.UniqueIdMaxLength)]
        [Display(Name = "Account/IBAN")]
        public string UniqueId { get; set; }

        [Required]
        [MaxLength(ModelConstants.User.FullNameMaxLength)]
        [Display(Name = "Beneficiary's name")]
        public string UserFullName { get; set; }
    }
}

Web/BankSystem.Web/Areas/MoneyTransfers/Models/Global/Create/GlobalMoneyTransferCreateDestinationBankDto.cs
namespace BankSystem.Web.Areas.MoneyTransfers.Models.Global.Create
{
    using System.ComponentModel.DataAnnotations;
    using Common;

    public class GlobalMoneyTransferCreateDestinationBankDto
    {
        [Required]
        [MaxLength(ModelConstants.BankAccount.SwiftCodeMaxLength)]
        [Display(Name = "Swift/Bank code")]
        public string SwiftCode { get; set; }

        [Required]
        [MaxLength(ModelConstants.BankAccount.NameMaxLength)]
        public string Name { get; set; }

        [Required]
        [MaxLength(ModelConstants.BankAccount.CountryMaxLength)]
        public string Country { get; set; }

        [Required]
        public GlobalMoneyTransferCreateDestinationAccountDto Account { get; set; }
    }
}

Web/BankSystem.Web/Models/BankAccount/BankAccountCreateBindingModel.cs
namespace BankSystem.Web.Models.BankAccount
{
    using System.ComponentModel.DataAnnotations;
    using Common.AutoMapping.Interfaces;
    using Services.Models.BankAccount;

    public class BankAccountCreateBindingModel : IMapWith<BankAccountCreateServiceModel>
    {
        [MaxLength(50)]
        public string Name { get; set; }
    }
}

Web/BankSystem.Web/Models/BankAccount/BankAccountDetailsViewModel.cs
namespace BankSystem.Web.Models.BankAccount
{
    using System;
    using Areas.MoneyTransfers.Models;
    using Common.AutoMapping.Interfaces;
    using Infrastructure.Collections;
    using Services.Models.BankAccount;

    public class BankAccountDetailsViewModel : IMapWith<BankAccountDetailsServiceModel>
    {
        public string Id { get; set; }

        public string Name { get; set; }

        public decimal Balance { get; set; }

        public string UniqueId { get; set; }

        public DateTime CreatedOn { get; set; }

        public string UserFullName { get; set; }

        public PaginatedList<MoneyTransferListingDto> MoneyTransfers { get; set; }

        public int MoneyTransfersCount { get; set; }

        public string BankName { get; set; }

        public string BankCode { get; set; }

        public string BankCountry { get; set; }
    }
}

Web/BankSystem.Web/Models/BankAccount/BankAccountIndexViewModel.cs
namespace BankSystem.Web.Models.BankAccount
{
    using Common.AutoMapping.Interfaces;
    using Services.Models.BankAccount;

    public class BankAccountIndexViewModel : IMapWith<BankAccountIndexServiceModel>
    {
        public string Id { get; set; }

        public string Name { get; set; }

        public decimal Balance { get; set; }

        public string UniqueId { get; set; }
    }
}

Web/BankSystem.Web/Models/BankAccount/OwnBankAccountListingViewModel.cs
namespace BankSystem.Web.Models.BankAccount
{
    using Common.AutoMapping.Interfaces;
    using Services.Models.BankAccount;

    public class OwnBankAccountListingViewModel : IMapWith<BankAccountIndexServiceModel>
    {
        public string Id { get; set; }

        public string Name { get; set; }

        public decimal Balance { get; set; }

        public string UniqueId { get; set; }
    }
}

Web/BankSystem.Web/Controllers/BankAccountsController.cs
namespace BankSystem.Web.Controllers
{
    using System;
    using System.Linq;
    using System.Threading.Tasks;
    using Areas.MoneyTransfers.Models;
    using AutoMapper;
    using Common;
    using Common.Configuration;
    using Infrastructure.Extensions;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.Extensions.Options;
    using Models.BankAccount;
    using Services.BankAccount;
    using Services.Models.BankAccount;
    using Services.Models.MoneyTransfer;
    using Services.MoneyTransfer;

    public class BankAccountsController : BaseController
    {
        private const int ItemsPerPage = 10;

        private readonly IBankAccountService bankAccountService;
        private readonly BankConfiguration bankConfiguration;
        private readonly IMoneyTransferService moneyTransferService;
        private readonly IMapper mapper;

        public BankAccountsController(
            IBankAccountService bankAccountService,
            IMoneyTransferService moneyTransferService,
            IOptions<BankConfiguration> bankConfigurationOptions,
            IMapper mapper)
        {
            this.bankAccountService = bankAccountService;
            this.moneyTransferService = moneyTransferService;
            this.mapper = mapper;
            this.bankConfiguration = bankConfigurationOptions.Value;
        }

        public IActionResult Create()
            => this.View();

        [HttpPost]
        public async Task<IActionResult> Create(BankAccountCreateBindingModel model)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(model);
            }

            var serviceModel = this.mapper.Map<BankAccountCreateServiceModel>(model);
            serviceModel.UserId = this.GetCurrentUserId();

            var accountId = await this.bankAccountService.CreateAsync(serviceModel);
            if (accountId == null)
            {
                this.ShowErrorMessage(NotificationMessages.BankAccountCreateError);

                return this.View(model);
            }

            this.ShowSuccessMessage(NotificationMessages.BankAccountCreated);

            return this.RedirectToAction("Index", "Home");
        }

        public async Task<IActionResult> Details(string id, int pageIndex = 1)
        {
            pageIndex = Math.Max(1, pageIndex);

            var account = await this.bankAccountService.GetByIdAsync<BankAccountDetailsServiceModel>(id);
            if (account == null ||
                account.UserId != this.GetCurrentUserId())
            {
                return this.Forbid();
            }

            var allTransfersCount = await this.moneyTransferService.GetCountOfAllMoneyTransfersForAccountAsync(id);
            var transfers = (await this.moneyTransferService
                    .GetMoneyTransfersForAccountAsync<MoneyTransferListingServiceModel>(id, pageIndex, ItemsPerPage))
                .Select(this.mapper.Map<MoneyTransferListingDto>)
                .ToPaginatedList(allTransfersCount, pageIndex, ItemsPerPage);

            var viewModel = this.mapper.Map<BankAccountDetailsViewModel>(account);
            viewModel.MoneyTransfers = transfers;
            viewModel.MoneyTransfersCount = allTransfersCount;
            viewModel.BankName = this.bankConfiguration.BankName;
            viewModel.BankCode = this.bankConfiguration.UniqueIdentifier;
            viewModel.BankCountry = this.bankConfiguration.Country;

            return this.View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> ChangeAccountNameAsync(string accountId, string name)
        {
            if (name == null)
            {
                return this.Ok(new
                {
                    success = false
                });
            }

            var account = await this.bankAccountService.GetByIdAsync<BankAccountDetailsServiceModel>(accountId);
            if (account == null ||
                account.UserId != this.GetCurrentUserId())
            {
                return this.Ok(new
                {
                    success = false
                });
            }

            bool isSuccessful = await this.bankAccountService.ChangeAccountNameAsync(accountId, name);

            return this.Ok(new
            {
                success = isSuccessful
            });
        }
    }
}

Web/BankSystem.Web/Views/BankAccounts/Create.cshtml
@model BankAccountCreateBindingModel

@{
    ViewData["Title"] = "Create bank account";
}

<div class="text-center w-md-75 w-lg-50 mx-auto my-4">
    <h2>@ViewData["Title"]</h2>
    <form method="post">
        <hr class="w-75"/>
        <div asp-validation-summary="All" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="Name">
                Display name
                <span class="text-muted font-italic">(optional)</span>
            </label>
            <input class="form-control" asp-for="Name"/>
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="form-group">
            <a class="btn btn-outline-secondary" asp-controller="Home" asp-action="Index">Cancel</a>
            <button type="submit" class="btn btn-primary">Create</button>
        </div>
    </form>
</div>

Web/BankSystem.Web/Views/BankAccounts/Details.cshtml
@model BankAccountDetailsViewModel
@{
    ViewData["Title"] = Model.UniqueId;
}

<div class="card mb-3">
    <div class="card-body hover-parent">
        <h2 class="card-title text-center">
            <span id="accountName">@Model.Name</span>
            <i class="fas fa-pen fa-xs cursor-pointer hover-visible text-muted text-primary-hover"
               data-toggle="modal" data-target="#editModal">
            </i>
        </h2>

        <div class="row">
            <div class="col-12 col-md-6 col-lg-5">
                <h5 class="text-center">Account details</h5>
                <div class="d-flex flex-row justify-content-between">
                    <p>Name</p>
                    <p class="ml-3">@Model.UserFullName</p>
                </div>
                <div class="d-flex flex-row justify-content-between">
                    <p>Current balance</p>
                    <p class="text-green ml-3">€@Model.Balance</p>
                </div>
                <div class="d-flex flex-row justify-content-between">
                    <p>Account number</p>
                    <p class="ml-3">@Model.UniqueId</p>
                </div>
                <div class="d-flex flex-row justify-content-between">
                    <p>Date of creation</p>
                    <p class="ml-3 auto-format-date">@Model.CreatedOn.ToString("O")</p>
                </div>
                <div class="d-flex flex-row justify-content-between">
                    <p>Total transfers</p>
                    <p class="ml-3">@Model.MoneyTransfersCount</p>
                </div>
            </div>
            <div class="col-12 col-md-6 offset-lg-2 col-lg-5">
                <h5 class="text-center">Transfer information</h5>
                <div class="d-flex flex-row justify-content-between">
                    <p>Name</p>
                    <p class="ml-3">@Model.UserFullName</p>
                </div>
                <div class="d-flex flex-row justify-content-between">
                    <p>Account</p>
                    <p class="ml-3">@Model.UniqueId</p>
                </div>
                <div class="d-flex flex-row justify-content-between">
                    <p>Bank name</p>
                    <p class="ml-3">@Model.BankName</p>
                </div>
                <div class="d-flex flex-row justify-content-between">
                    <p>Bank country</p>
                    <p class="ml-3">@Model.BankCountry</p>
                </div>
                <div class="d-flex flex-row justify-content-between">
                    <p>Bank code</p>
                    <p class="ml-3">@Model.BankCode</p>
                </div>
            </div>
        </div>

    </div>
</div>

@if (!Model.MoneyTransfers.Any())
{
    <h5 class="text-center text-muted">No money transfers have been made yet</h5>
}
else
{
    <h3 class="text-center">Last transfers</h3>
    <table class="table table-hover table-bordered auto-datatable">
        <thead>
        <tr>
            <th data-priority="2">Date</th>
            <th data-priority="4">Details</th>
            <th data-priority="3">From</th>
            <th data-priority="5">To</th>
            <th data-priority="1">Amount</th>
            <th class="none">Reference number</th>

        </tr>
        </thead>
        <tbody>
        @foreach (var moneyTransfer in Model.MoneyTransfers)
        {
            <tr>
                <td class="auto-format-date">@moneyTransfer.MadeOn.ToString("O")</td>
                <td class="word-break-all">@moneyTransfer.Description</td>
                <td>
                    <p>@moneyTransfer.SenderName</p>
                    <p>@moneyTransfer.Source</p>
                </td>
                <td>
                    <p>@moneyTransfer.RecipientName</p>
                    <p>@moneyTransfer.Destination</p>
                </td>
                <td>
                    @if (moneyTransfer.Amount < 0)
                    {
                        <span class="text-red">@moneyTransfer.Amount EUR</span>
                    }
                    else
                    {
                        <span class="text-green">+@moneyTransfer.Amount EUR</span>
                    }
                </td>
                <td>@moneyTransfer.ReferenceNumber</td>
            </tr>
        }
        </tbody>
    </table>

    <partial name="_PaginationPartial" model="@Model.MoneyTransfers"/>
}

<div id="editModal" class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Edit account display name</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form method="post">
                    <input type="hidden" name="accountId" value="@Model.Id">
                    <div class="form-group">
                        <label>Name</label>
                        <input required class="form-control" type="text" name="name">
                    </div>
                    <div class="text-center d-flex justify-content-between">
                        <button type="button" class="btn btn-secondary mr-auto" data-dismiss="modal">Cancel</button>
                        <button type="submit" class="btn btn-primary">OK</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@section Scripts
{
    <script>
        $('#editModal').on('show.bs.modal',
            function() {
                let modal = $(this);
                let name = $('#accountName').text();

                modal.find('.modal-body input[name=name]').val(name);
            });

        $('#editModal').on('shown.bs.modal',
            function() {
                $(this).find('.modal-body input[name=name]').trigger('focus');
            });

        $('#editModal form').submit(function(event) {
            event.preventDefault();

            $.ajax({
                url: '@Url.Action("ChangeAccountNameAsync", "BankAccounts")',
                type: 'post',
                data: $(event.target).serialize()

            }).always(function() {
                $('#editModal').modal('hide');
            }).done(function(response) {
                if (!response.success) {
                    return;
                }

                let newName = $('#editModal input[name=name]').val();

                $('#accountName').text(newName);
            });
        });
    </script>
}